import CardCar from "../../../assets/images/card_car.png"
import car1 from "../../../assets/images/car1.jpeg"
import car2 from "../../../assets/images/car2.jpeg"
import car3 from "../../../assets/images/car3.jpeg"
const fakeCarCollection = [
  {
    src: CardCar,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car1,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
  {
    src: car2,

    id: "1679659375126",
    name: "dzialaaaaaa",
    carLink: "www.google.com",
    year: "2045",
    colors: ["white", "orange", "black"],
    brand: "opel astra",
    series: "Matchbox",
    tags: ["kustosz", "perla", "nie mam pomyslu xd"],
    description: "random desc",
    collectionsId: [""],
    owneruserid: "1679306069692",
  },
]

export default fakeCarCollection
